return {
  "nvim-treesitter/nvim-treesitter-textobjects",
  branch = "main",
  lazy = true,
  event = { "BufReadPost", "BufNewFile" },
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
  },
  config = function()
    require("nvim-treesitter-textobjects").setup({
      select = {
        lookahead = true,
      },
      move = {
        set_jumps = true,
      },
    })

    local select = require("nvim-treesitter-textobjects.select")
    local move = require("nvim-treesitter-textobjects.move")
    local swap = require("nvim-treesitter-textobjects.swap")

    local keymap = vim.keymap.set

    keymap({ "x", "o" }, "a=", function()
      select.select_textobject("@assignment.outer", "textobjects")
    end, { desc = "Select outer part of an assignment" })
    keymap({ "x", "o" }, "i=", function()
      select.select_textobject("@assignment.inner", "textobjects")
    end, { desc = "Select inner part of an assignment" })
    keymap({ "x", "o" }, "l=", function()
      select.select_textobject("@assignment.lhs", "textobjects")
    end, { desc = "Select left hand side of an assignment" })
    keymap({ "x", "o" }, "r=", function()
      select.select_textobject("@assignment.rhs", "textobjects")
    end, { desc = "Select right hand side of an assignment" })

    keymap({ "x", "o" }, "a:", function()
      select.select_textobject("@property.outer", "textobjects")
    end, { desc = "Select outer part of an object property" })
    keymap({ "x", "o" }, "i:", function()
      select.select_textobject("@property.inner", "textobjects")
    end, { desc = "Select inner part of an object property" })
    keymap({ "x", "o" }, "l:", function()
      select.select_textobject("@property.lhs", "textobjects")
    end, { desc = "Select left part of an object property" })
    keymap({ "x", "o" }, "r:", function()
      select.select_textobject("@property.rhs", "textobjects")
    end, { desc = "Select right part of an object property" })

    keymap({ "x", "o" }, "aa", function()
      select.select_textobject("@parameter.outer", "textobjects")
    end, { desc = "Select outer part of a parameter/argument" })
    keymap({ "x", "o" }, "ia", function()
      select.select_textobject("@parameter.inner", "textobjects")
    end, { desc = "Select inner part of a parameter/argument" })

    keymap({ "x", "o" }, "ai", function()
      select.select_textobject("@conditional.outer", "textobjects")
    end, { desc = "Select outer part of a conditional" })
    keymap({ "x", "o" }, "ii", function()
      select.select_textobject("@conditional.inner", "textobjects")
    end, { desc = "Select inner part of a conditional" })

    keymap({ "x", "o" }, "al", function()
      select.select_textobject("@loop.outer", "textobjects")
    end, { desc = "Select outer part of a loop" })
    keymap({ "x", "o" }, "il", function()
      select.select_textobject("@loop.inner", "textobjects")
    end, { desc = "Select inner part of a loop" })

    keymap({ "x", "o" }, "af", function()
      select.select_textobject("@call.outer", "textobjects")
    end, { desc = "Select outer part of a function call" })
    keymap({ "x", "o" }, "if", function()
      select.select_textobject("@call.inner", "textobjects")
    end, { desc = "Select inner part of a function call" })

    keymap({ "x", "o" }, "am", function()
      select.select_textobject("@function.outer", "textobjects")
    end, { desc = "Select outer part of a method/function definition" })
    keymap({ "x", "o" }, "im", function()
      select.select_textobject("@function.inner", "textobjects")
    end, { desc = "Select inner part of a method/function definition" })

    keymap({ "x", "o" }, "ac", function()
      select.select_textobject("@class.outer", "textobjects")
    end, { desc = "Select outer part of a class" })
    keymap({ "x", "o" }, "ic", function()
      select.select_textobject("@class.inner", "textobjects")
    end, { desc = "Select inner part of a class" })

    keymap("n", "<leader>na", function()
      swap.swap_next("@parameter.inner")
    end, { desc = "Swap parameters/argument with next" })
    keymap("n", "<leader>n:", function()
      swap.swap_next("@property.outer")
    end, { desc = "Swap object property with next" })
    keymap("n", "<leader>nm", function()
      swap.swap_next("@function.outer")
    end, { desc = "Swap function with next" })
    keymap("n", "<leader>pa", function()
      swap.swap_previous("@parameter.inner")
    end, { desc = "Swap parameters/argument with prev" })
    keymap("n", "<leader>p:", function()
      swap.swap_previous("@property.outer")
    end, { desc = "Swap object property with prev" })
    keymap("n", "<leader>pm", function()
      swap.swap_previous("@function.outer")
    end, { desc = "Swap function with previous" })

    keymap({ "n", "x", "o" }, "]f", function()
      move.goto_next_start("@call.outer", "textobjects")
    end, { desc = "Next function call start" })
    keymap({ "n", "x", "o" }, "]m", function()
      move.goto_next_start("@function.outer", "textobjects")
    end, { desc = "Next method/function def start" })
    keymap({ "n", "x", "o" }, "]c", function()
      move.goto_next_start("@class.outer", "textobjects")
    end, { desc = "Next class start" })
    keymap({ "n", "x", "o" }, "]i", function()
      move.goto_next_start("@conditional.outer", "textobjects")
    end, { desc = "Next conditional start" })
    keymap({ "n", "x", "o" }, "]l", function()
      move.goto_next_start("@loop.outer", "textobjects")
    end, { desc = "Next loop start" })
    keymap({ "n", "x", "o" }, "]s", function()
      move.goto_next_start("@local.scope", "locals")
    end, { desc = "Next scope" })
    keymap({ "n", "x", "o" }, "]z", function()
      move.goto_next_start("@fold", "folds")
    end, { desc = "Next fold" })

    keymap({ "n", "x", "o" }, "]F", function()
      move.goto_next_end("@call.outer", "textobjects")
    end, { desc = "Next function call end" })
    keymap({ "n", "x", "o" }, "]M", function()
      move.goto_next_end("@function.outer", "textobjects")
    end, { desc = "Next method/function def end" })
    keymap({ "n", "x", "o" }, "]C", function()
      move.goto_next_end("@class.outer", "textobjects")
    end, { desc = "Next class end" })
    keymap({ "n", "x", "o" }, "]I", function()
      move.goto_next_end("@conditional.outer", "textobjects")
    end, { desc = "Next conditional end" })
    keymap({ "n", "x", "o" }, "]L", function()
      move.goto_next_end("@loop.outer", "textobjects")
    end, { desc = "Next loop end" })

    keymap({ "n", "x", "o" }, "[f", function()
      move.goto_previous_start("@call.outer", "textobjects")
    end, { desc = "Prev function call start" })
    keymap({ "n", "x", "o" }, "[m", function()
      move.goto_previous_start("@function.outer", "textobjects")
    end, { desc = "Prev method/function def start" })
    keymap({ "n", "x", "o" }, "[c", function()
      move.goto_previous_start("@class.outer", "textobjects")
    end, { desc = "Prev class start" })
    keymap({ "n", "x", "o" }, "[i", function()
      move.goto_previous_start("@conditional.outer", "textobjects")
    end, { desc = "Prev conditional start" })
    keymap({ "n", "x", "o" }, "[l", function()
      move.goto_previous_start("@loop.outer", "textobjects")
    end, { desc = "Prev loop start" })

    keymap({ "n", "x", "o" }, "[F", function()
      move.goto_previous_end("@call.outer", "textobjects")
    end, { desc = "Prev function call end" })
    keymap({ "n", "x", "o" }, "[M", function()
      move.goto_previous_end("@function.outer", "textobjects")
    end, { desc = "Prev method/function def end" })
    keymap({ "n", "x", "o" }, "[C", function()
      move.goto_previous_end("@class.outer", "textobjects")
    end, { desc = "Prev class end" })
    keymap({ "n", "x", "o" }, "[I", function()
      move.goto_previous_end("@conditional.outer", "textobjects")
    end, { desc = "Prev conditional end" })
    keymap({ "n", "x", "o" }, "[L", function()
      move.goto_previous_end("@loop.outer", "textobjects")
    end, { desc = "Prev loop end" })
  end,
}
